[build]
  base = ""
  publish = "packages/playground/build"
  command = "npm run bootstrap && (npm run build || { sleep 120; false; }) && cd packages/playground && npm run build:playground"

[build.environment]
  SHOW_NETLIFY_BADGE = "true"
