[build]
  base = ""
  publish = "packages/playground/build"
  command = "npm run bootstrap && npm run build && cd packages/playground && npm run publish-to-gh-pages"

[build.environment]
  SHOW_NETLIFY_BADGE = "true"
